function [SpikeTimes Stim V t] = hhou_call(DC,SD,SampleRate,StimTime,SpikeThreshold,G_in)
% [SpikeTimes V t] = hhou_call(DC,SD,SampleRate,StimTime,G_in)
%
% This function calls hh.mexmac, which implements a Hodgkin-Huxley model
% neuron that is integrated via a fixed time step Runge-Kutta ODE solver.
% The stimulus is generated by an Ornstein-Uhlenbeck Gaussian-Markov
% stochastic process, which is equivalent to exponentially filtered
% Gaussian white noise. The output voltage and stimulus are downsampled to 
% 4 kHz.
%
% Inputs:
% DC                mean of stimulus
% SD                standard deviation of stimulus
% SampleRate        inverse of time step (Hz)
% StimTime          length of stimulus (sec)
% G_in              maximal conductances for sodium, potassium, and leak;
%                   standard values are [1.2 0.36 .003] mS/mm^2
%
% SpikeThreshold    threshold for detecting a spike
% Outputs:
% SpikeTimes        vector of spike times (sec)
% V                 1xn vector of voltage
% t                 time vector (sec)
%
%-------------------------------------------------------------------------
% BN Lundstrom, 2006-9

% If the requested StimTime creates vectors that are too long for Matlab, a
% loop will be implemented. NOTE: the pieces are NOT contiguous.

st_count = 0.2;
yi = [-65 0.3177 0.0529 0.5961];

TT = 60; %max sec allowed for 1 repetition
if StimTime <= TT
    StimBit1 = [];
    [Sp St y t] = hhou_call2(DC,SD,SampleRate,StimTime,SpikeThreshold,G_in,yi,st_count,StimBit1);
    SpikeTimes = Sp;
    Stim = St;
    V = y(1,:);
else
    reps = floor(StimTime/TT);
    last_rep = rem(StimTime,TT);
    if last_rep > 0
        T = [TT*ones(1,reps) last_rep];
    else
        T = [TT*ones(1,reps)];
    end
    Stim = zeros(1,StimTime*4000); %sampled at 4 kHz
    V = zeros(1,StimTime*4000);
    t = zeros(1,StimTime*4000);
    SpikeTimes = [];
    CT = [0 cumsum(T)];
    StimBit1 = [];
        
    for i = 1:length(T)
        [Sp St V2 t2 yo SB2] = hhou_call2(DC,SD,SampleRate,T(i),SpikeThreshold,G_in,yi,st_count,StimBit1);
        SpikeTimes = [SpikeTimes Sp+CT(i)];
        Stim((CT(i)*4000+1):(CT(i+1)*4000)) = St;
        V((CT(i)*4000+1):(CT(i+1)*4000)) = V2;
        t((CT(i)*4000+1):(CT(i+1)*4000)) = t2+CT(i)*1000;
        yi = yo';
        st_count = 0;
        StimBit1 = SB2;
    end
end

function [SpikeTimes Stim V t yo SB2] = hhou_call2(DC,SD,SampleRate,StimTime,SpikeThreshold,G_in, yi, st_count, StimBit1)
% generation of stimulus with 1 msec tau; add 200 msec to beginning of
% stimulus to ensure that initial values of the model aren't crucial

% ST_COUNT is sec before counting spikes.
tspan(1) = 0;
tspan(2) = StimTime*1000+st_count*1000;
dt = 1000/SampleRate;
%stim = OU(tspan(2)/1000+1/(2*SampleRate), 1/(2*SampleRate), DC, SD, 0.001);
[stim SB2] = make_stim(tspan(2)/1000-st_count+1/SampleRate,DC,SD^2,2*SampleRate,StimBit1);
Stim = [zeros(1,st_count*2000/dt) stim]; %ensure that initial values don't play a role

% call hh model and generate spike train
%[t y] = hh(Stim, tspan, dt, G_in, yi);
[t y] = morrislecar(Stim,tspan,dt,G_in,[-60 0.015]);
if max(y(1,:))>100 || min(y(1,:))<-150 || sum(isnan(y(1,:)))>0
    error('Voltage out of bounds!***************************************'),
end;
spike_times = findspikes(y(1,:),SpikeThreshold,SampleRate);
tmp = min(find(spike_times>st_count));
SpikeTimes = spike_times(tmp:length(spike_times))-st_count;
y = y(:,(st_count*SampleRate+1):end);
t = t((st_count*SampleRate+1):end)-st_count*1000;

% downsample to 4 kHz
delta = ceil(SampleRate/4000);
Stim = stim(2*delta+1:2*delta:end);
V = y(1,(delta+1:delta:end));
t = t(delta+1:delta:end);
yo = y(:,end);

return